
spring:
  profiles:
     active:
     - dev

---
spring:
  profiles: dev
  application:
    name: springCloud-config-dwil-dev
---
spring:
  profiles: test
  application:
    name: springCloud-config-dwil-test
# 请保存为UTF-8
